// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all MaintenanceRecords
export async function GET() {
  try {
    const items = await prisma.maintenancerecord.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching MaintenanceRecords:', error);
    return NextResponse.json(
      { error: 'Failed to fetch MaintenanceRecords' },
      { status: 500 }
    );
  }
}

// POST create new MaintenanceRecord
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.maintenancerecord.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating MaintenanceRecord:', error);
    return NextResponse.json(
      { error: 'Failed to create MaintenanceRecord' },
      { status: 500 }
    );
  }
}

// PUT update MaintenanceRecord
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.maintenancerecord.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating MaintenanceRecord:', error);
    return NextResponse.json(
      { error: 'Failed to update MaintenanceRecord' },
      { status: 500 }
    );
  }
}

// DELETE MaintenanceRecord
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.maintenancerecord.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting MaintenanceRecord:', error);
    return NextResponse.json(
      { error: 'Failed to delete MaintenanceRecord' },
      { status: 500 }
    );
  }
}
