// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Categorys
export async function GET() {
  try {
    const items = await prisma.category.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Categorys:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Categorys' },
      { status: 500 }
    );
  }
}

// POST create new Category
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.category.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Category:', error);
    return NextResponse.json(
      { error: 'Failed to create Category' },
      { status: 500 }
    );
  }
}

// PUT update Category
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.category.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Category:', error);
    return NextResponse.json(
      { error: 'Failed to update Category' },
      { status: 500 }
    );
  }
}

// DELETE Category
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.category.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Category:', error);
    return NextResponse.json(
      { error: 'Failed to delete Category' },
      { status: 500 }
    );
  }
}
