// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Transactions
export async function GET() {
  try {
    const items = await prisma.transaction.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Transactions:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Transactions' },
      { status: 500 }
    );
  }
}

// POST create new Transaction
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.transaction.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Transaction:', error);
    return NextResponse.json(
      { error: 'Failed to create Transaction' },
      { status: 500 }
    );
  }
}

// PUT update Transaction
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.transaction.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Transaction:', error);
    return NextResponse.json(
      { error: 'Failed to update Transaction' },
      { status: 500 }
    );
  }
}

// DELETE Transaction
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.transaction.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Transaction:', error);
    return NextResponse.json(
      { error: 'Failed to delete Transaction' },
      { status: 500 }
    );
  }
}
