// Generated by Helix v4.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '../../../lib/prisma';

// GET all Todos
export async function GET() {
    try {
        const items = await prisma.todo.findMany({
            orderBy: { createdAt: 'desc' },
        });
        return NextResponse.json(items);
    } catch (error) {
        console.error('Error fetching Todos:', error);
        return NextResponse.json(
            { error: 'Failed to fetch Todos' },
            { status: 500 }
        );
    }
}

// POST create new Todo
export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const item = await prisma.todo.create({
            data: {
                title: body.title,
                priority: body.priority || 1,
                is_completed: body.is_completed || false,
            },
        });
        return NextResponse.json(item, { status: 201 });
    } catch (error) {
        console.error('Error creating Todo:', error);
        return NextResponse.json(
            { error: 'Failed to create Todo' },
            { status: 500 }
        );
    }
}

// PUT update Todo
export async function PUT(request: NextRequest) {
    try {
        const body = await request.json();
        const { id, ...data } = body;

        const item = await prisma.todo.update({
            where: { id },
            data,
        });
        return NextResponse.json(item);
    } catch (error) {
        console.error('Error updating Todo:', error);
        return NextResponse.json(
            { error: 'Failed to update Todo' },
            { status: 500 }
        );
    }
}

// DELETE Todo
export async function DELETE(request: NextRequest) {
    try {
        const { searchParams } = new URL(request.url);
        const id = searchParams.get('id');

        if (!id) {
            return NextResponse.json(
                { error: 'ID is required' },
                { status: 400 }
            );
        }

        await prisma.todo.delete({
            where: { id },
        });
        return NextResponse.json({ success: true });
    } catch (error) {
        console.error('Error deleting Todo:', error);
        return NextResponse.json(
            { error: 'Failed to delete Todo' },
            { status: 500 }
        );
    }
}
