// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Agents
export async function GET() {
  try {
    const items = await prisma.agent.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Agents:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Agents' },
      { status: 500 }
    );
  }
}

// POST create new Agent
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.agent.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Agent:', error);
    return NextResponse.json(
      { error: 'Failed to create Agent' },
      { status: 500 }
    );
  }
}

// PUT update Agent
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.agent.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Agent:', error);
    return NextResponse.json(
      { error: 'Failed to update Agent' },
      { status: 500 }
    );
  }
}

// DELETE Agent
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.agent.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Agent:', error);
    return NextResponse.json(
      { error: 'Failed to delete Agent' },
      { status: 500 }
    );
  }
}
