// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Ingredients
export async function GET() {
  try {
    const items = await prisma.ingredient.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Ingredients:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Ingredients' },
      { status: 500 }
    );
  }
}

// POST create new Ingredient
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.ingredient.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Ingredient:', error);
    return NextResponse.json(
      { error: 'Failed to create Ingredient' },
      { status: 500 }
    );
  }
}

// PUT update Ingredient
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.ingredient.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Ingredient:', error);
    return NextResponse.json(
      { error: 'Failed to update Ingredient' },
      { status: 500 }
    );
  }
}

// DELETE Ingredient
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.ingredient.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Ingredient:', error);
    return NextResponse.json(
      { error: 'Failed to delete Ingredient' },
      { status: 500 }
    );
  }
}
