// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Expenses
export async function GET() {
  try {
    const items = await prisma.expense.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Expenses:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Expenses' },
      { status: 500 }
    );
  }
}

// POST create new Expense
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.expense.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Expense:', error);
    return NextResponse.json(
      { error: 'Failed to create Expense' },
      { status: 500 }
    );
  }
}

// PUT update Expense
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.expense.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Expense:', error);
    return NextResponse.json(
      { error: 'Failed to update Expense' },
      { status: 500 }
    );
  }
}

// DELETE Expense
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.expense.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Expense:', error);
    return NextResponse.json(
      { error: 'Failed to delete Expense' },
      { status: 500 }
    );
  }
}
