// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Missions
export async function GET() {
  try {
    const items = await prisma.mission.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Missions:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Missions' },
      { status: 500 }
    );
  }
}

// POST create new Mission
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.mission.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Mission:', error);
    return NextResponse.json(
      { error: 'Failed to create Mission' },
      { status: 500 }
    );
  }
}

// PUT update Mission
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.mission.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Mission:', error);
    return NextResponse.json(
      { error: 'Failed to update Mission' },
      { status: 500 }
    );
  }
}

// DELETE Mission
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.mission.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Mission:', error);
    return NextResponse.json(
      { error: 'Failed to delete Mission' },
      { status: 500 }
    );
  }
}
