// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Intels
export async function GET() {
  try {
    const items = await prisma.intel.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Intels:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Intels' },
      { status: 500 }
    );
  }
}

// POST create new Intel
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.intel.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Intel:', error);
    return NextResponse.json(
      { error: 'Failed to create Intel' },
      { status: 500 }
    );
  }
}

// PUT update Intel
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.intel.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Intel:', error);
    return NextResponse.json(
      { error: 'Failed to update Intel' },
      { status: 500 }
    );
  }
}

// DELETE Intel
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.intel.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Intel:', error);
    return NextResponse.json(
      { error: 'Failed to delete Intel' },
      { status: 500 }
    );
  }
}
