// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Logs
export async function GET() {
  try {
    const items = await prisma.log.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Logs:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Logs' },
      { status: 500 }
    );
  }
}

// POST create new Log
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.log.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Log:', error);
    return NextResponse.json(
      { error: 'Failed to create Log' },
      { status: 500 }
    );
  }
}

// PUT update Log
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.log.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Log:', error);
    return NextResponse.json(
      { error: 'Failed to update Log' },
      { status: 500 }
    );
  }
}

// DELETE Log
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.log.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Log:', error);
    return NextResponse.json(
      { error: 'Failed to delete Log' },
      { status: 500 }
    );
  }
}
