// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Vehicles
export async function GET() {
  try {
    const items = await prisma.vehicle.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Vehicles:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Vehicles' },
      { status: 500 }
    );
  }
}

// POST create new Vehicle
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.vehicle.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Vehicle:', error);
    return NextResponse.json(
      { error: 'Failed to create Vehicle' },
      { status: 500 }
    );
  }
}

// PUT update Vehicle
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.vehicle.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Vehicle:', error);
    return NextResponse.json(
      { error: 'Failed to update Vehicle' },
      { status: 500 }
    );
  }
}

// DELETE Vehicle
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.vehicle.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Vehicle:', error);
    return NextResponse.json(
      { error: 'Failed to delete Vehicle' },
      { status: 500 }
    );
  }
}
