// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Reminders
export async function GET() {
  try {
    const items = await prisma.reminder.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Reminders:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Reminders' },
      { status: 500 }
    );
  }
}

// POST create new Reminder
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.reminder.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Reminder:', error);
    return NextResponse.json(
      { error: 'Failed to create Reminder' },
      { status: 500 }
    );
  }
}

// PUT update Reminder
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.reminder.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Reminder:', error);
    return NextResponse.json(
      { error: 'Failed to update Reminder' },
      { status: 500 }
    );
  }
}

// DELETE Reminder
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.reminder.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Reminder:', error);
    return NextResponse.json(
      { error: 'Failed to delete Reminder' },
      { status: 500 }
    );
  }
}
