// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Recipes
export async function GET() {
  try {
    const items = await prisma.recipe.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Recipes:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Recipes' },
      { status: 500 }
    );
  }
}

// POST create new Recipe
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.recipe.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Recipe:', error);
    return NextResponse.json(
      { error: 'Failed to create Recipe' },
      { status: 500 }
    );
  }
}

// PUT update Recipe
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.recipe.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Recipe:', error);
    return NextResponse.json(
      { error: 'Failed to update Recipe' },
      { status: 500 }
    );
  }
}

// DELETE Recipe
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.recipe.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Recipe:', error);
    return NextResponse.json(
      { error: 'Failed to delete Recipe' },
      { status: 500 }
    );
  }
}
