// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Traders
export async function GET() {
  try {
    const items = await prisma.trader.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Traders:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Traders' },
      { status: 500 }
    );
  }
}

// POST create new Trader
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.trader.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Trader:', error);
    return NextResponse.json(
      { error: 'Failed to create Trader' },
      { status: 500 }
    );
  }
}

// PUT update Trader
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.trader.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Trader:', error);
    return NextResponse.json(
      { error: 'Failed to update Trader' },
      { status: 500 }
    );
  }
}

// DELETE Trader
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.trader.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Trader:', error);
    return NextResponse.json(
      { error: 'Failed to delete Trader' },
      { status: 500 }
    );
  }
}
