// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all ServiceLogs
export async function GET() {
  try {
    const items = await prisma.serviceLog.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching ServiceLogs:', error);
    return NextResponse.json(
      { error: 'Failed to fetch ServiceLogs' },
      { status: 500 }
    );
  }
}

// POST create new ServiceLog
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.serviceLog.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating ServiceLog:', error);
    return NextResponse.json(
      { error: 'Failed to create ServiceLog' },
      { status: 500 }
    );
  }
}

// PUT update ServiceLog
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;

    const item = await prisma.serviceLog.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating ServiceLog:', error);
    return NextResponse.json(
      { error: 'Failed to update ServiceLog' },
      { status: 500 }
    );
  }
}

// DELETE ServiceLog
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }

    await prisma.serviceLog.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting ServiceLog:', error);
    return NextResponse.json(
      { error: 'Failed to delete ServiceLog' },
      { status: 500 }
    );
  }
}
