// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Nodes
export async function GET() {
  try {
    const items = await prisma.node.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Nodes:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Nodes' },
      { status: 500 }
    );
  }
}

// POST create new Node
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.node.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Node:', error);
    return NextResponse.json(
      { error: 'Failed to create Node' },
      { status: 500 }
    );
  }
}

// PUT update Node
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.node.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Node:', error);
    return NextResponse.json(
      { error: 'Failed to update Node' },
      { status: 500 }
    );
  }
}

// DELETE Node
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.node.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Node:', error);
    return NextResponse.json(
      { error: 'Failed to delete Node' },
      { status: 500 }
    );
  }
}
