// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Photos
export async function GET() {
  try {
    const items = await prisma.photo.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Photos:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Photos' },
      { status: 500 }
    );
  }
}

// POST create new Photo
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.photo.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Photo:', error);
    return NextResponse.json(
      { error: 'Failed to create Photo' },
      { status: 500 }
    );
  }
}

// PUT update Photo
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.photo.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Photo:', error);
    return NextResponse.json(
      { error: 'Failed to update Photo' },
      { status: 500 }
    );
  }
}

// DELETE Photo
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.photo.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Photo:', error);
    return NextResponse.json(
      { error: 'Failed to delete Photo' },
      { status: 500 }
    );
  }
}
