/**
 * Helix Page Generator — Multi-page app generation
 * Generates layouts, navigation, and per-page route components for Next.js App Router
 */

import { HelixPage, HelixStrand } from './parser';

/**
 * Generate a root layout with navigation between pages
 */
export function generateLayout(pages: HelixPage[], appName: string): string {
  const navLinks = pages
    .map(p => `          <Link href="${p.route}" className="px-4 py-2 rounded-lg hover:bg-white/10 transition-colors">${p.name}</Link>`)
    .join('\n');

  return `import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "${appName}",
  description: "Generated by Helix v11.0",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900">
          {/* Navigation */}
          <nav className="border-b border-white/10 bg-black/20 backdrop-blur-xl">
            <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
              <h1 className="text-xl font-bold text-white">${appName}</h1>
              <div className="flex gap-2 text-sm text-gray-300">
${navLinks}
              </div>
            </div>
          </nav>

          {/* Page Content */}
          <main className="max-w-7xl mx-auto px-6 py-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
`;
}

/**
 * Generate a sidebar layout variant
 */
export function generateSidebarLayout(pages: HelixPage[], appName: string): string {
  const navLinks = pages
    .map(p => `            <Link href="${p.route}" className="block px-4 py-2 rounded-lg hover:bg-white/10 transition-colors text-gray-300 hover:text-white">${p.name}</Link>`)
    .join('\n');

  return `import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "${appName}",
  description: "Generated by Helix v11.0",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900">
          {/* Sidebar */}
          <aside className="w-64 border-r border-white/10 bg-black/30 backdrop-blur-xl p-6">
            <h1 className="text-xl font-bold text-white mb-8">${appName}</h1>
            <nav className="flex flex-col gap-1 text-sm">
${navLinks}
            </nav>
          </aside>

          {/* Main Content */}
          <main className="flex-1 p-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
`;
}

/**
 * Generate a page component that displays CRUD for its assigned strands
 */
export function generatePageComponent(page: HelixPage, strands: HelixStrand[]): string {
  const pageStrands = strands.filter(s => page.strands.includes(s.name));

  if (pageStrands.length === 0) {
    return `'use client';

export default function ${page.name}Page() {
  return (
    <div>
      <h1 className="text-2xl font-bold text-white mb-4">${page.name}</h1>
      <p className="text-gray-400">No data models assigned to this page.</p>
    </div>
  );
}
`;
  }

  const imports: string[] = [`'use client';`, `import { useState, useEffect } from 'react';`];
  const stateDecls: string[] = [];
  const fetchCalls: string[] = [];
  const sections: string[] = [];

  for (const strand of pageStrands) {
    const name = strand.name;
    const lower = name.toLowerCase();
    const plural = lower + 's';

    stateDecls.push(`  const [${plural}, set${name}s] = useState<any[]>([]);`);
    stateDecls.push(`  const [${lower}Loading, set${name}Loading] = useState(true);`);

    fetchCalls.push(`    fetch('/api/${plural}')
      .then(r => r.json())
      .then(d => { set${name}s(d.data || d); set${name}Loading(false); })
      .catch(() => set${name}Loading(false));`);

    const fieldCols = strand.fields.slice(0, 5).map(f =>
      `              <th className="text-left p-3 text-gray-400 text-sm font-medium">${f.name}</th>`
    ).join('\n');

    const fieldCells = strand.fields.slice(0, 5).map(f =>
      `              <td className="p-3 text-gray-300">{String(item.${f.name} ?? '')}</td>`
    ).join('\n');

    sections.push(`
        {/* ${name} Section */}
        <section className="bg-white/5 rounded-2xl border border-white/10 p-6">
          <h2 className="text-lg font-semibold text-white mb-4">${name}s</h2>
          {${lower}Loading ? (
            <p className="text-gray-400">Loading...</p>
          ) : ${plural}.length === 0 ? (
            <p className="text-gray-400">No ${plural} found.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="border-b border-white/10">
                  <tr>
${fieldCols}
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {${plural}.map((item: any, i: number) => (
                    <tr key={item.id || i} className="hover:bg-white/5">
${fieldCells}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </section>`);
  }

  return `${imports.join('\n')}

export default function ${page.name}Page() {
${stateDecls.join('\n')}

  useEffect(() => {
${fetchCalls.join('\n')}
  }, []);

  return (
    <div className="space-y-8">
      <h1 className="text-2xl font-bold text-white">${page.name}</h1>
${sections.join('\n')}
    </div>
  );
}
`;
}

/**
 * Generate a redirect page.tsx for the app root that goes to the first page
 */
export function generateRootRedirect(firstRoute: string): string {
  return `import { redirect } from 'next/navigation';

export default function Home() {
  redirect('${firstRoute}');
}
`;
}
