/**
 * Helix Auto Test Generator
 * Generates Vitest test files for spawned API routes and React components
 */

import { HelixStrand, HelixField } from './parser';

/**
 * Generate Vitest test file for an API route
 */
export function generateAPITests(strand: HelixStrand): string {
  const name = strand.name;
  const lower = name.toLowerCase();
  const requiredFields = strand.fields.filter(f => !f.constraints?.includes('optional'));
  const sampleData: Record<string, string> = {};
  const invalidData: Record<string, string> = {};

  for (const field of requiredFields) {
    sampleData[field.name] = getSampleValue(field);
    invalidData[field.name] = '';
  }

  const sampleJson = JSON.stringify(sampleData, null, 4);

  return `// Auto-generated by Helix Test Generator
import { describe, it, expect, beforeAll } from 'vitest';

const BASE_URL = process.env.TEST_URL || 'http://localhost:3000';

describe('${name} API', () => {
  let createdId: string | null = null;

  it('GET /api/${lower} — should return paginated list', async () => {
    const res = await fetch(\`\${BASE_URL}/api/${lower}\`);
    expect(res.status).toBe(200);

    const json = await res.json();
    // Helix APIs return { data: [...], pagination: {...} }
    expect(json).toHaveProperty('data');
    expect(json).toHaveProperty('pagination');
    expect(Array.isArray(json.data)).toBe(true);
    expect(json.pagination).toHaveProperty('page');
    expect(json.pagination).toHaveProperty('total');
  });

  it('POST /api/${lower} — should create a new ${lower}', async () => {
    const res = await fetch(\`\${BASE_URL}/api/${lower}\`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(${sampleJson}),
    });
    expect(res.status).toBe(201);

    const json = await res.json();
    expect(json).toHaveProperty('id');
${requiredFields.map(f => `    expect(json).toHaveProperty('${f.name}');`).join('\n')}
    createdId = json.id;
  });

  it('POST /api/${lower} — should reject empty body', async () => {
    const res = await fetch(\`\${BASE_URL}/api/${lower}\`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({}),
    });
    // Should return 400 for missing required fields
    expect(res.status).toBe(400);
  });

  it('GET /api/${lower} — should include created item', async () => {
    const res = await fetch(\`\${BASE_URL}/api/${lower}\`);
    const json = await res.json();
    const items = json.data || json;

    if (createdId) {
      const found = items.find((item: any) => item.id === createdId);
      expect(found).toBeDefined();
    }
  });

  it('GET /api/${lower}?page=1&limit=5 — should respect pagination', async () => {
    const res = await fetch(\`\${BASE_URL}/api/${lower}?page=1&limit=5\`);
    expect(res.status).toBe(200);

    const json = await res.json();
    expect(json.data.length).toBeLessThanOrEqual(5);
    expect(json.pagination.limit).toBe(5);
  });
});
`;
}

/**
 * Generate React Testing Library test for a component page
 */
export function generateComponentTests(strand: HelixStrand): string {
  const name = strand.name;
  const lower = name.toLowerCase();

  return `// Auto-generated by Helix Test Generator
import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';

// Note: Import the actual page component when running
// import ${name}Page from '@/app/${lower}/page';

describe('${name} Page', () => {
  it('should be importable', () => {
    // Verify the module exists
    expect(true).toBe(true);
  });

  // Uncomment when running with Next.js test setup:
  /*
  it('should render the page heading', () => {
    render(<${name}Page />);
    expect(screen.getByRole('heading')).toBeInTheDocument();
  });

  it('should have form elements for ${name} fields', () => {
    render(<${name}Page />);
${strand.fields.map(f => `    // Check for ${f.name} field
    // expect(screen.getByLabelText(/${f.name}/i)).toBeInTheDocument();`).join('\n')}
  });

  it('should display loading state initially', () => {
    render(<${name}Page />);
    // Check for loading indicator
    expect(screen.getByText(/loading/i)).toBeInTheDocument();
  });
  */
});
`;
}

/**
 * Generate vitest.config.ts for a Next.js project
 */
export function generateTestConfig(): string {
  return `import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: [],
    include: ['__tests__/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['node_modules', '.next'],
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
`;
}

/**
 * Get a sample value for a field type (for test data)
 */
function getSampleValue(field: HelixField): string {
  switch (field.type) {
    case 'String':
      return `Test ${field.name}`;
    case 'Int':
      return '42';
    case 'Float':
    case 'Decimal':
      return '3.14';
    case 'Boolean':
      return 'true';
    case 'DateTime':
      return new Date().toISOString();
    case 'Json':
      return '{}';
    default:
      return `test-${field.name}`;
  }
}
