// Generated by Helix v3.0
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all Assets
export async function GET() {
  try {
    const items = await prisma.asset.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(items);
  } catch (error) {
    console.error('Error fetching Assets:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Assets' },
      { status: 500 }
    );
  }
}

// POST create new Asset
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.asset.create({
      data: body,
    });
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    console.error('Error creating Asset:', error);
    return NextResponse.json(
      { error: 'Failed to create Asset' },
      { status: 500 }
    );
  }
}

// PUT update Asset
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, ...data } = body;
    
    const item = await prisma.asset.update({
      where: { id },
      data,
    });
    return NextResponse.json(item);
  } catch (error) {
    console.error('Error updating Asset:', error);
    return NextResponse.json(
      { error: 'Failed to update Asset' },
      { status: 500 }
    );
  }
}

// DELETE Asset
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'ID is required' },
        { status: 400 }
      );
    }
    
    await prisma.asset.delete({
      where: { id },
    });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Asset:', error);
    return NextResponse.json(
      { error: 'Failed to delete Asset' },
      { status: 500 }
    );
  }
}
